export const SHOP_LIST_REQUEST = 'SHOP_LIST_REQUEST'
export const SHOP_LIST_SUCCESS = 'SHOP_LIST_SUCCESS'
export const SHOP_LIST_FAIL = 'SHOP_LIST_FAIL'

export const SHOP_DETAILS_REQUEST = 'SHOP_DETAILS_REQUEST'
export const SHOP_DETAILS_SUCCESS = 'SHOP_DETAILS_SUCCESS'
export const SHOP_DETAILS_FAIL = 'SHOP_DETAILS_FAIL'

export const SHOP_DELETE_REQUEST = 'SHOP_DELETE_REQUEST'
export const SHOP_DELETE_SUCCESS = 'SHOP_DELETE_SUCCESS'
export const SHOP_DELETE_FAIL = 'SHOP_DELETE_FAIL'

export const SELLER_SHOP_DETAILS_REQUEST = 'SELLER_SHOP_DETAILS_REQUEST'
export const SELLER_SHOP_DETAILS_SUCCESS = 'SELLER_SHOP_DETAILS_SUCCESS'
export const SELLER_SHOP_DETAILS_FAIL = 'SELLER_SHOP_DETAILS_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'
