export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const DETAILS_REQUEST = 'DETAILS_REQUEST'
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS'
export const DETAILS_FAIL = 'DETAILS_FAIL'

export const UPDATE_DETAILS_REQUEST = 'UPDATE_DETAILS_REQUEST'
export const UPDATE_DETAILS_SUCCESS = 'UPDATE_DETAILS_SUCCESS'
export const UPDATE_DETAILS_FAIL = 'UPDATE_DETAILS_FAIL'
